before_install:
  - sudo add-apt-repository -y ppa:ondrej/php
  - sudo apt-get update
  - sudo apt-get install -y php7.3-cli
  - sudo cp -vf "$(command -v php7.3)" "$(command -v php)"
before_script: make
script: make test
after_script: make clean
